config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: 'homes#top'
  get '/books', to: 'books#index', as: 'books'
  get '/books/:id', to: 'books#show', as: 'book'
  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  delete '/books/:id', to: 'books#destroy', as: 'destroy_book'
  post '/books', to: 'books#create', as: 'create_books'
  patch '/books/:id', to: 'books#update', as: 'update_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully created.'
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      render 'edit'
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local: true do |f| %>
  <h2>Editing Book</h2>
  <% if @book.errors.any? %>
    <div id="errorExplanation">
      <h2>
        <%= pluralize(@book.errors.count, "error")%> prohibited this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <div>
    <span>
      <%= f.submit 'Update Book' %>
    </span>
  </div>
<% end %>
<%= link_to 'Show', book_path(@book.id) %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h4><%= notice %></h4>

<h2>Books</h2>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to 'Show', book_path(book.id) %></td>
      <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
      <td><%= link_to 'Destroy', destroy_book_path(book.id), method: :delete %></td>
    </tr>
  <% end %>
  </tr>
</table>

<section>
  <h2>New book</h2>
  <%= form_with model: @book, url: create_books_path, method: :post, local: true do |f| %>
    <% if @book.errors.any? %>
      <div id="errorExplanation">
        <h2>
          <%= pluralize(@book.errors.count, "error")%> prohibited this book from being saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div><%= f.label :title %></div>
    <%= f.text_field :title %>
    <div><%= f.label :body %></div>
    <%= f.text_area :body %>
    <div>
      <%= f.submit 'Create Book'%>
    </div>
  <% end %>
</section>

app/views/books/show.html.erb
<h4><%= notice %></h4>
<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそBookersへ</h1>
<p>
  Bookersでは、さまざまな書籍に関するあなたの意見や<br/>
  <br/>
  印象を共有し交換することができます
</p>
<%= link_to 'start', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>